FROM ubuntu:20.04

RUN apt-get update

RUN apt-get install -y curl 

RUN mkdir /usr/paquete

RUN curl -SL https://github.com/phayes/geoPHP/tarball/master/phayes-geoPHP-1.2-20-g6855624.tar.gz \
   | tar -xzC /usr/paquete \
