version: '3.6'

services:
    elasticsearch:
      image: elasticsearch:7.9.3
      container_name: elasticsearch-01
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - discovery.type=single-node
      networks:
        - elastic

    kibana:
      image: kibana:7.9.3
      container_name: kibana-01
      ports:
        - 5601:5601
      environment:
        - ELASTICSEARCH_HOST=elasticsearch
        - ELASTICSEARCH_PORT=9200
      networks:
        - elastic
      depends_on:
        - elasticsearch

networks:
  elastic: 
    driver: bridge 
