FROM ubuntu:20.04

ADD https://github.com/phayes/geoPHP/tarball/master/phayes-geoPHP-1.2-20-g6855624.tar.gz usr/paquete/

RUN tar -xzf /usr/paquete/phayes-geoPHP-1.2-20-g6855624.tar.gz -C usr/paquete \
  && rm usr/paquete/phayes-geoPHP-1.2-20-g6855624.tar.gz

